import React from 'react';
import SalesNav from '../comp/SalesNav';
import './Blog1.css'; // Assuming you will use a CSS file for styling
import Footer from '../components/Footer';
export default function Blog1() {
  return (
    <div>
      <SalesNav />
      <br></br><br></br><br></br><br></br><br></br><br></br><br></br>
      <div className="blog-container">
        <img
          src="https://via.placeholder.com/600x400" 
          alt="Centered Photo"
          className="centered-photo"
        />
        <p className="lorem-text">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. 
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper.
        </p>
        <p className="lorem-text">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. 
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at nisl arcu. Morbi vel turpis a massa dignissim eleifend. Aenean sed magna sit amet lorem vulputate ullamcorper.
        </p>
      </div>
      <br></br><br></br><br></br><br></br><br></br><br></br><br></br>
      <Footer />
    </div>
  );
}
